#(c) A+ Computer Science
#www.apluscompsci.com


import pygame
from pygame.locals import *

def drawSquares(window):
    # Create variables to keep track of size and position
    
    # Use a loop to draw squares until the size is too small
    
    pass
        
        
def drawCircles(window):
    # Create variables to keep track of size, position and color
    
    # Use a loop to draw circles until the size is too small

    pass
